In [2]:
a=1
b=2
c=3
d=4

In [3]:
a+b, a-b, a*c

(3, -1, 3)

In [9]:
print(a+b)
print(a+b, a-b, a*c)

3
3 -1 3


In [12]:
print(a*b)
print(d/b)
print(d%c)

1010
2.0
1


In [10]:
a=input()

 10


In [11]:
type(a)

str

In [13]:
a=int(input())

 10


In [14]:
type(a)

int

In [15]:
a=float(input())

 10


In [16]:
type(a)

float

In [33]:
a = 123
b = -123
c = 0

In [34]:
type(a)

int

In [35]:
a = 1.2
b = -2.1

In [36]:
type(b)

float

In [37]:
a = 1.24e-2

In [38]:
a

0.0124

In [39]:
b=1.24E2

In [40]:
b

124.0

In [17]:
10<15

True

In [20]:
print(bool(2))

True


In [21]:
print(bool(""))

False


In [22]:
print(bool("hi!"))

True


In [25]:
not 1 == 1

False

In [27]:
1 != 1

False

In [28]:
python = 'python'

In [29]:
a="python"
b=2

In [30]:
a*b

'pythonpython'

In [31]:
food = "python's favorite food is perl"

In [32]:
type(food)

str

In [41]:
print("="*50)
print("My Program")
print("="*50)

My Program


In [32]:
A = [1, 2, 3, 4, 5]

In [33]:
type(A)

list

In [30]:
B = list[1,2,3,4,5]

In [31]:
type(B)

types.GenericAlias

In [24]:
c = [1,2,3,4]

In [25]:
type(c)

list

In [38]:
a="독고영재,50"
b="김철수,30"
slist = ["독고영재,50","김철수,30"]

In [35]:
alist=[a,b]

In [36]:
alist

[['독고영재,50'], '김철수,30']

In [51]:
slist

['독고영재,50', '김철수,30']

In [43]:
a = [1,2,3]
b = [5,6,7]
c=a+b
type(c)


list

In [53]:
a = [1,2,3,"a"]
b = [5,6,7,"b"]
c=a+b
type(c)

list

In [54]:
c

[1, 2, 3, 'a', 5, 6, 7, 'b']

In [48]:
import numpy as np

In [59]:
a=np.array([1,2,3])
b=np.array([5,6,7])

In [60]:
a

array([1, 2, 3])

In [61]:
b

array([5, 6, 7])

In [45]:
c=a+b

In [44]:
type(c)

list

In [64]:
c.shape

(3,)

In [49]:
a=np.array([1,2,3,'a'])
b=np.array([5,6,7,'b'])

In [50]:
a

array(['1', '2', '3', 'a'], dtype='<U21')

In [51]:
b

array(['5', '6', '7', 'b'], dtype='<U21')

In [53]:
c=a+b

In [85]:
print(c)

['15' '26' '37' 'ab']


In [67]:
type(c)

numpy.ndarray

In [73]:
c.shape

(4,)

In [71]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[5,6,7], [8,9,10]])

In [72]:
c = a + b
type(c)

numpy.ndarray

In [73]:
c

array([[ 6,  8, 10],
       [12, 14, 16]])

In [77]:
c.shape

(2, 3)

In [78]:
print(c)

[[ 6  8 10]
 [12 14 16]]


In [79]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [80]:
a.shape

(1, 3, 3)

In [1]:
A = "안녕하십니까 저는 강원대학교학생입니다."

In [16]:
A = ["독고영재-50",["김철수-30"]]


In [22]:
A[1][0][0:4]

'김철수-'