In [1]:
A = "안녕하세요 지금은 데이터 전처리 수업 시간입니다."
A[0:4]

'안녕하세'

In [2]:
A[-1]

'.'

In [4]:
A[-5:]

'간입니다.'

In [5]:
A[:-5]

'안녕하세요 지금은 데이터 전처리 수업 시'

In [8]:
A[21:23]

'시간'

In [3]:
A[-6:-4]

'시간'

In [35]:
print(("당신의 영어성적은 {}점입니다. 그리고 수학 성적은 {}점 입니다.").format(70,80))

당신의 영어성적은 70점입니다. 그리고 수학 성적은 80점 입니다.


In [37]:
print(("{:.2f},{:.3f}").format(3.1415,3.1415))

3.14,3.142


In [38]:
url = "https://www.youtube.com/"

In [48]:
str = url.replace("https://","")

In [46]:
str1 = url.replace("youtube","naver")

In [47]:
print(url)
print(str)
print(str1)

https://www.youtube.com/
www.youtube.com/
https://www.naver.com/


In [50]:
A = ["독고영재,50","김철수,30"]
type(A)

list

In [53]:
type(A[0])

str

In [54]:
A[0][0:4]

'독고영재'

In [63]:
a=["독고영재,50","김철수,30"]

In [64]:
b=["김철수,20","김영희,25"]

In [61]:
a.index(",")

4

In [80]:
a[0][:a[0].index(",")]

'독고영재'

In [81]:
b[1][:b[1].index(",")]

'김영희'

In [17]:
a=["hi", 10, "80","김철수",50,50.6]

In [5]:
a.append(1)

In [16]:
a

['hi', 10, '80', '김철수', 50.6]

In [7]:
a.pop(6)

1

In [21]:
a

['hi', 10, '김철수', 50, 50.6]

In [18]:
a.index(50)

4

In [10]:
a.pop(4)

50

In [19]:
b=a.index("80")

In [20]:
a.pop(b)

'80'

In [25]:
import numpy as np

In [26]:
a=np.array([1,2,3,4])

In [27]:
a

array([1, 2, 3, 4])

In [28]:
a=np.array([1,2,3,4,5])

In [29]:
a=np.delete(a,[1,3])

In [30]:
a

array([1, 3, 5])

In [31]:
a=a[a<=4]

In [32]:
a

array([1, 3])

In [37]:
a=[a!=4]

In [38]:
a

[True]

In [39]:
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[5,6],[7,8]])

In [40]:
merged_array = np.vstack((array1,array2))

In [41]:
print(merged_array)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [42]:
merged_array = np.hstack((array1,array2))

In [43]:
print(merged_array)

[[1 2 5 6]
 [3 4 7 8]]


In [44]:
A={1:"김철수", 20:"박영희"}

In [45]:
A[1]

'김철수'

In [160]:
A[20]

'박영희'

In [163]:
A[2]

KeyError: 2

In [165]:
A.get(1)

'김철수'

In [171]:
print(A.get(2))

None


In [182]:
A={"1-A":"김철수","20-B":"박영희"}

In [183]:
A["2-A"] = "영희"

In [184]:
A

{'1-A': '김철수', '20-B': '박영희', '2-A': '영희'}

In [194]:
del A["20-B"]

KeyError: '20-B'

In [187]:
A

{'1-A': '김철수', '2-A': '영희'}

In [189]:
a={
    "1-A":[1,2,3,4,5],
    "20-B":["A","B","C","D","E"]
}

In [191]:
a

{'1-A': [1, 2, 3, 4, 5], '20-B': ['A', 'B', 'C', 'D', 'E']}

In [63]:
a=np.array([1,2,3,4])
a = np.append(a,[4,5])

In [58]:
a

array([1, 2, 3, 4, 4, 5])

In [64]:
a=np.insert(a,2,[6,8])

In [65]:
a

array([1, 2, 6, 8, 3, 4, 4, 5])